version: "3.8"
services:
  hazelcast:
    image: hazelcast/hazelcast:5.3.0
    ports:
    - "5701:5701"
    volumes:
      - ./custom-config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml

  management-center:
    image: hazelcast/management-center:5.3.0
    ports:
    - "7777:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast